# DO NOT **delete** OR **modify** any keys
# JUST **change** values in condition
# Service will be crashed if some keys missing

# build from [https://github.com/dajk/hltv-api]
# hltv-api: https://hltv-api.vercel.app
hltv-api: https://selfhost-hltv-api.vercel.app/

# if enable localtime format or enable utc format
time_format:
  localtime: true
  time_delta: +8    # UTC+8:00 for Peking

# filter match records as your wish
match_filter:
  enable: true
  # only these teams match will be parsed
  # FULL TEAM NAME NEEDED
  team_whitelist: [
    "Astralis", "Natus Vincere", "Vitality", "BIG", "Liquid",
    "Virtus.pro", "Heroic", "mousesports", "FURIA", "fnatic",
    "G2", "OG", "Spirit", "Complexity", "Gambit", "Evil Geniuses",
    "FunPlus Phoenix", "NIP", "FaZe", "Cloud9", "MIBR", "forZe", "SAW"
  ]
  match_max_count: 10

map_support: [
  "de_inferno", "de_nuke", "de_train", "de_vertigo",
  "de_mirage", "de_overpass", "de_ancient", "de_dust2"
]
